server:
  port: 8762

spring:
  application:
    name: provider
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/20066
    username: root
    password: root
  #连接Mongodb
  data:
    mongodb:
      uri: mongodb://localhost:27017/20065
  #redis连接
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0
  main:
    allow-bean-definition-overriding: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  #mybatisxml文件的地址
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

